provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  youtubedl:
    lang: Dockerfile
    handler: ./
    image: rgee0/faas-youtubedl:0.4
    environment:
      read_timeout: 300s
      write_timeout: 300s
    labels: 
      com.openfaas.ui.ext: "mp4"
